name: CustomCommands
version: '1.0-SNAPSHOT'
main: me.stephenmcode.customCommands.CustomCommands
api-version: '1.21'
authors: [ StephenMCode ]
description: Testing out the creation and implementation of custom commands
commands:
  god:
    description: Become invincible
    usage: /<command>
